name: Deploy landing dev

on:
  push:
    branches: [dev]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_firebase-hosting.yml
    with:
      environment: Development
      firebase_config: firebase.dev.json
      firebase_project: clipealo-gpt-amigos-dev
      site_url: https://landing.dev.clipealo-ai.com
